# Generated by Django 2.1.5 on 2019-02-28 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import toc.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=60)),
                ('author', models.TextField(max_length=60)),
                ('year', models.PositiveIntegerField()),
                ('publisher', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=60)),
                ('cover_img', models.FileField(default='default_book_cover.jpg', upload_to=toc.utils.MediaFiles.upload_path)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
