# Generated by Django 2.1.4 on 2019-02-03 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookcrossing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
