# Generated by Django 2.1.4 on 2019-01-14 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_on',
            field=models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now)),
        ),
    ]
