# Generated by Django 2.1.4 on 2019-01-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_post_last_edited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='last_edited_on',
        ),
    ]
